version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Europe/Berlin'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Europe/Berlin'
