name: "Setup node, pnpm and dependencies"
inputs:
  node-version:
    description: "Node version to use"
    required: true
    default: 20
  runner-os:
    description: "Runner os to use"
    required: true
    default: "ubuntu-latest"
  cache:
    description: "Cache to use"
    required: true
    default: "pnpm"
runs:
  using: "composite"
  steps:
    - run: echo Setting up node and dependencies ${{ inputs.node-version }} and ${{ inputs.runner-os }}
      shell: bash
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
        cache: ${{ inputs.cache }}
    - name: Install dependencies
      run: pnpm i
      shell: bash
