name: "Setup node, pnpm and dependencies"
inputs:
  node-version:
    description: "Node version to use"
    required: true
    default: 24
  runner-os:
    description: "Runner os to use"
    required: true
    default: "ubuntu-latest"
  cache:
    description: "Cache to use"
    required: true
    default: "pnpm"
runs:
  using: "composite"
  steps:
    - run: echo Setting up node and dependencies ${{ inputs.node-version }} and ${{ inputs.runner-os }}
      shell: bash
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 9
    - name: Setup node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
        cache: ${{ inputs.cache }}
    - name: Install dependencies
      run: pnpm i
      shell: bash
