name: 🚧 Build, Lint and Test

on:
  pull_request:
  push:
    branches:
       - master

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: setup-node-and-pnpm
        uses: ./.github/actions/setup-node-and-pnpm-dependencies
      - name: Lint code
        run: pnpm lint

  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [26, 24, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: setup-node-and-pnpm
        uses: ./.github/actions/setup-node-and-pnpm-dependencies
        with:
          node-version: ${{ matrix.version }}
          runner-os: ${{ matrix.os }}
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
