name: 🧪 E2E Test

on:
  pull_request:
  push:
    branches:
       - master

jobs:
  e2e-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # TODO: add macos-latest
        version: [20, 22, 24]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: setup-node-and-pnpm
        uses: ./.github/actions/setup-node-and-pnpm-dependencies
        with:
          node-version: ${{ matrix.version }}
          runner-os: ${{ matrix.os }}
          cache: 'pnpm'
      - name: Build
        run: pnpm build
      - name: Pack
        run: pnpm pack
      - name: Install
        run: pnpm install -g $(pwd)/git-jira-branch-*.tgz
        shell: bash
      - name: Run E2E tests
        env:
          JIRA_API_TOKEN: ${{ secrets.GCJB_JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.GCJB_USER_EMAIL }}
          JIRA_API_URL: ${{ vars.GCJB_JIRA_API_URL }}
          JIRA_KEY_PREFIX: ${{ vars.GCJB_JIRA_KEY_PREFIX }}
          GIT_JB_BIN: 'git-jira-branch'
        run: pnpm e2e-test:ci
