permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - master
name: 🤖 Release please!
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          command: manifest
          target-branch: master
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
      - id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        if: ${{ steps.release.outputs.release_created }}
      - id: setup-node-and-pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/setup-node-and-pnpm-dependencies
      - run: |
        # Ensure npm 11.5.1 or later is installed
        npm install -g npm@latest
        npm publish
        if: ${{ steps.release.outputs.release_created }}
